spring.application.name=pocket_plant

server.port=8080

# Database Configuration // MySQL ?????? ?? ?? (????? ??? ?????)
spring.datasource.url=jdbc:mysql://localhost:3306/pocket_plant
spring.datasource.username=root
spring.datasource.password=19g61t61r!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Configuration
jwt.secret=fjeoiFEIPjpfpwhifMJFIPIE*ut0833fij08y9)21-3288-1492190s)DjfpJEFjodkMMMEIfiefp21231WDW*__)2fjpeefpfejifIJ@JofoffeWWWdefuee
jwt.expiration=3600000*24*3

# Kakao API Configuration (Mobile API)
kakao.api.user-info-url=https://kapi.kakao.com/v2/user/me
kakao.rest-api-key=674b8ac1621693ca0b258ef9a4a19495

